#!/usr/bin/env python3
"""Validate catalog metadata and regenerate the bilingual README sections."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog" / "skills.json"
READMES = {"en": ROOT / "README.md", "pt": ROOT / "README.pt-BR.md"}
START = "<!-- CATALOG:START -->"
END = "<!-- CATALOG:END -->"
ID_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

CATEGORIES = [
    ("official", "Official collection", "Coleção oficial"),
    ("development", "Development", "Desenvolvimento"),
    ("data-research", "Data & research", "Dados e pesquisa"),
    ("design-media", "Design & media", "Design e mídia"),
    ("productivity-collaboration", "Productivity & collaboration", "Produtividade e colaboração"),
    ("security-quality", "Security & quality", "Segurança e qualidade"),
]
ALLOWED = {
    "kind": {"skill", "plugin", "collection"},
    "provenance": {"openai-catalog", "community"},
    "surface": {"chat", "work", "codex"},
    "category": {item[0] for item in CATEGORIES},
}
REQUIRED = {
    "id", "name", "kind", "publisher", "category", "summary_en",
    "summary_pt_br", "url", "provenance", "license", "surfaces", "checked_on",
}

LABELS = {
    "en": {
        "kind": {"skill": "Skill", "plugin": "Plugin", "collection": "Collection"},
        "provenance": {"openai-catalog": "OpenAI catalog", "community": "Community"},
        "surface": {"chat": "Chat", "work": "Work", "codex": "Codex"},
        "license": "License",
        "generated": "Generated by scripts/catalog.py. Do not edit this block manually.",
    },
    "pt": {
        "kind": {"skill": "Skill", "plugin": "Plugin", "collection": "Coleção"},
        "provenance": {"openai-catalog": "Catálogo OpenAI", "community": "Comunidade"},
        "surface": {"chat": "Chat", "work": "Work", "codex": "Codex"},
        "license": "Licença",
        "generated": "Gerado por scripts/catalog.py. Não edite este bloco manualmente.",
    },
}


def load_catalog() -> dict:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def validate_catalog(data: dict) -> list[str]:
    errors: list[str] = []
    if data.get("schema_version") != 1:
        errors.append("schema_version must be 1")
    entries = data.get("entries")
    if not isinstance(entries, list) or not entries:
        return errors + ["entries must be a non-empty array"]

    seen_ids: set[str] = set()
    seen_urls: set[str] = set()
    for index, entry in enumerate(entries):
        where = f"entries[{index}]"
        if not isinstance(entry, dict):
            errors.append(f"{where} must be an object")
            continue
        missing = REQUIRED - entry.keys()
        extra = entry.keys() - REQUIRED
        if missing:
            errors.append(f"{where} missing: {', '.join(sorted(missing))}")
        if extra:
            errors.append(f"{where} unknown fields: {', '.join(sorted(extra))}")
        if missing:
            continue

        entry_id = entry["id"]
        if not isinstance(entry_id, str) or not ID_RE.fullmatch(entry_id):
            errors.append(f"{where}.id must use lowercase letters, digits, and hyphens")
        elif entry_id in seen_ids:
            errors.append(f"duplicate id: {entry_id}")
        seen_ids.add(entry_id)

        for field in ("name", "publisher", "summary_en", "summary_pt_br", "license"):
            if not isinstance(entry[field], str) or not entry[field].strip():
                errors.append(f"{where}.{field} must be a non-empty string")
        if str(entry["license"]).casefold() == "unspecified":
            errors.append(f"{where}.license may not be Unspecified")
        if entry["kind"] not in ALLOWED["kind"]:
            errors.append(f"{where}.kind is invalid")
        if entry["provenance"] not in ALLOWED["provenance"]:
            errors.append(f"{where}.provenance is invalid")
        if entry["category"] not in ALLOWED["category"]:
            errors.append(f"{where}.category is invalid")

        surfaces = entry["surfaces"]
        if not isinstance(surfaces, list) or not surfaces or len(surfaces) != len(set(surfaces)):
            errors.append(f"{where}.surfaces must be a non-empty unique array")
        elif set(surfaces) - ALLOWED["surface"]:
            errors.append(f"{where}.surfaces contains an invalid value")

        url = entry["url"]
        parsed = urlparse(url) if isinstance(url, str) else None
        if not parsed or parsed.scheme != "https" or not parsed.netloc:
            errors.append(f"{where}.url must be an absolute HTTPS URL")
        elif url in seen_urls:
            errors.append(f"duplicate url: {url}")
        seen_urls.add(url)
        try:
            date.fromisoformat(entry["checked_on"])
        except (TypeError, ValueError):
            errors.append(f"{where}.checked_on must be YYYY-MM-DD")
    return errors


def validate_repo_skills() -> list[str]:
    errors: list[str] = []
    for path in ROOT.glob(".agents/skills/*/SKILL.md"):
        text = path.read_text(encoding="utf-8")
        if "TODO" in text or not text.startswith("---\n"):
            errors.append(f"{path.relative_to(ROOT)} has unfinished or invalid frontmatter")
            continue
        end = text.find("\n---\n", 4)
        frontmatter = text[4:end] if end >= 0 else ""
        values = {}
        for line in frontmatter.splitlines():
            if ":" in line:
                key, value = line.split(":", 1)
                values[key.strip()] = value.strip().strip('"')
        name = values.get("name", "")
        description = values.get("description", "")
        if name != path.parent.name or not ID_RE.fullmatch(name):
            errors.append(f"{path.relative_to(ROOT)} name must match its folder")
        if len(description) < 40:
            errors.append(f"{path.relative_to(ROOT)} description is not discriminating")
        ui = path.parent / "agents" / "openai.yaml"
        if ui.exists() and f"${name}" not in ui.read_text(encoding="utf-8"):
            errors.append(f"{ui.relative_to(ROOT)} default prompt must mention ${name}")
    return errors


def render(entries: list[dict], language: str) -> str:
    labels = LABELS[language]
    lines: list[str] = []
    for category, title_en, title_pt in CATEGORIES:
        selected = sorted((e for e in entries if e["category"] == category), key=lambda e: e["name"].casefold())
        if not selected:
            continue
        lines.extend([f"### {title_en if language == 'en' else title_pt}", ""])
        for entry in selected:
            summary = entry["summary_en"] if language == "en" else entry["summary_pt_br"]
            tags = [labels["kind"][entry["kind"]], labels["provenance"][entry["provenance"]]]
            tags.extend(labels["surface"][surface] for surface in entry["surfaces"])
            tags.append(f"{labels['license']}: {entry['license']}")
            metadata = " · ".join(f"`{tag}`" for tag in tags)
            lines.append(
                f"- [**{entry['name']}**]({entry['url']}) — {summary} "
                f"{metadata} · {entry['publisher']} · {entry['checked_on']}"
            )
        lines.append("")
    return "\n".join(lines).rstrip()


def generated_readme(current: str, entries: list[dict], language: str) -> str:
    if current.count(START) != 1 or current.count(END) != 1:
        raise ValueError("README must contain exactly one catalog marker pair")
    comment = f"<!-- {LABELS[language]['generated']} -->"
    block = f"{START}\n{comment}\n\n{render(entries, language)}\n{END}"
    return re.sub(re.escape(START) + r".*?" + re.escape(END), block, current, flags=re.S)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    try:
        data = load_catalog()
    except (OSError, json.JSONDecodeError) as exc:
        print(f"catalog error: {exc}", file=sys.stderr)
        return 1
    errors = validate_catalog(data) + validate_repo_skills()
    for language, path in READMES.items():
        current = path.read_text(encoding="utf-8")
        try:
            expected = generated_readme(current, data["entries"], language)
        except ValueError as exc:
            errors.append(f"{path.name}: {exc}")
            continue
        if args.write:
            path.write_text(expected, encoding="utf-8")
        elif current != expected:
            errors.append(f"{path.name} catalog block is stale; run --write")

    if errors:
        print("Validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(f"Catalog valid: {len(data['entries'])} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
